development:
  adapter: postgresql
  database: blueashdb_development
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: blueashdb_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: blueashdb_production
  pool: 5
  timeout: 5000
